site_name: "Vlab"
site_description: "Vlab 维护文档"
site_author: 'iBug'
site_url: 'https://ibugone.com/vlab/'

# Repository
repo_name: 'iBug/vlab'
repo_url: 'https://github.com/iBug/vlab'

# Copyright
copyright: 'Copyright &copy; 2019-2020 iBug, USTCLUG and USTC Vlab'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'blue'
# feature:
#   tabs: true

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://vlab.ustc.edu.cn/'
    - type: 'github'
      link: 'https://github.com/USTC-vlab'

extra_javascript:
  - assets/js/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 概览: overview.md
  - SSH 证书认证: ssh-ca.md
  - 网络配置:
    - 网络界面: networking/index.md
    - 容器内网: networking/intranet.md
    - 防火墙与安全: networking/firewall.md
  - 工作流程:
    - 配置新主机: workflow/new-host.md

  - 历史版本:
    - 第一代: history/gen1.md
