site_name: "Vlab 维护文档"
site_description: "Vlab 维护文档"
site_author: 'iBug'
site_url: 'https://vlab.ibugone.com/'

# Repository
repo_name: 'USTC-vlab/maint-docs'
repo_url: 'https://github.com/USTC-vlab/maint-docs'

# Copyright
copyright: 'Copyright &copy; 2019-2021 iBug, USTCLUG and USTC Vlab'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  custom_dir: 'overrides/'
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: octicons/server-16
    repo: octicons/mark-github-16
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

# Customization
extra:
  social:
    - icon: octicons/globe-16
      link: 'https://vlab.ustc.edu.cn/'
    - icon: octicons/mark-github-16
      link: 'https://github.com/USTC-vlab'

extra_css:
  # Borrow CSS from user docs
  - 'https://vlab.ustc.edu.cn/docs/assets/css/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - markdown.extensions.def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs/assets/
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
      subscript: false
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 概览: overview.md
  - 备份: backup/index.md
  - SSH 证书认证: ssh-ca.md
  - 网络配置:
    - 网络界面: networking/index.md
    - 主机网卡: networking/host.md
    - 容器内网: networking/intranet.md
    - 防火墙与安全: networking/firewall.md
    - IP 地址列表: networking/ips.md
  - 服务主机:
    - 网关 (CT 100): servers/ct100.md
    - Web 服务器 (CT 101): servers/ct101.md
    - 备份服务器 (VM 104): servers/vm104.md
  - 用户界面:
    - VNC 统一登录: ui/vncmux.md
    - RDP 统一登录: ui/rdpproxy.md
  - Vlab 实验软件:
    - 配置: vlab-software/index.md
    - 软件安装: vlab-software/installation.md
  - KVM 虚拟机:
    - cloud-init 配置: kvm/cloud-init.md
  - 测试环境:
    - 简介: testbed/index.md
  - 工作流程:
    - 配置新主机: workflow/new-host.md
    - 打包容器镜像: workflow/pack-ct-image.md
    - 打包虚拟机镜像: workflow/pack-vm-image.md
    - 打包 Windows 镜像: workflow/pack-windows-image.md
    - 杂项: workflow/miscellaneous.md
  - 参考资料:
    - desktop 桌面图标文件: references/desktop.md
    - 统一身份认证: references/ustccas.md
    - Proxmox ID 分配表: references/pve-ids.md
  - 其他资料:
    - 踩坑记录: traps.md
    - 更新历史: changelog.md
    - 工作总结:
      - 2020 年 3 月 31 日: records/2020-03-31.md
      - 2020 年 8 月 1 日: records/2020-08-01.md
      - 2021 年 3 月 18 日: records/2021-03-18.md
      - 2021 年 6 月 13 日: records/2021-06-13.md
      - 2021 年 8 月 21 日: records/2021-08-21.md
      - 2021 年 8 月 28 日: records/2021-08-28.md
    - 历史版本:
      - 第一代: history/gen1.md
