site_name: "Vlab 维护文档"
site_description: "Vlab 维护文档"
site_author: 'iBug'
site_url: 'https://vlab.ibugone.com/'

# Repository
repo_name: 'USTC-vlab/maint-docs'
repo_url: 'https://github.com/USTC-vlab/maint-docs'

# Copyright
copyright: 'Copyright &copy; 2019-2020 iBug, USTCLUG and USTC Vlab'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: octicons/server-16
    repo: octicons/mark-github-16

# Customization
extra:
  social:
    - icon: octicons/globe-16
      link: 'https://vlab.ustc.edu.cn/'
    - icon: octicons/mark-github-16
      link: 'https://github.com/USTC-vlab'

extra_javascript:
  - assets/js/extra.js
  - 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/js/all.min.js'

extra_css:
  # Borrow CSS from Linux 101
  - 'https://101.ustclug.org/css/extra.css'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 首页: index.md
  - 概览: overview.md
  - SSH 证书认证: ssh-ca.md
  - 网络配置:
    - 网络界面: networking/index.md
    - 主机网卡: networking/host.md
    - 容器内网: networking/intranet.md
    - 防火墙与安全: networking/firewall.md
    - IP 地址列表: networking/ips.md
  - 服务主机:
    - 网关 (CT 100): servers/ct100.md
    - Web 服务器 (CT 101): servers/ct101.md
    - 备份服务器 (VM 104): servers/vm104.md
  - 远程桌面:
    - 配置与管理: vnc/config.md
  - Vlab 软件组合: vlab-software.md
  - cloud-init 配置: cloud-init.md
  - 备份: backup/index.md
  - 工作流程:
    - 配置新主机: workflow/new-host.md
    - 打包容器镜像: workflow/pack-ct-image.md
    - 打包虚拟机镜像: workflow/pack-vm-image.md
  - 参考资料:
    - "desktop 桌面图标文件": references/desktop.md
    - "统一身份认证": references/ustccas.md
  - 其他资料:
    - 踩坑记录: traps.md
    - 更新历史: changelog.md
    - 工作总结:
      - '2020 年 3 月 31 日': records/2020-03-31.md
      - '2020 年 8 月 1 日': records/2020-08-01.md
      - '2021 年 3 月 18 日': records/2021-03-18.md
      - '2021 年 6 月 13 日': records/2021-06-13.md
    - 历史版本:
      - 第一代: history/gen1.md
