site_name: "Vlab"
site_description: "Vlab 维护文档"
site_author: 'iBug'
site_url: 'https://ibugone.com/vlab/'

# Repository
repo_name: 'iBug/vlab'
repo_url: 'https://github.com/iBug/vlab'

# Copyright
copyright: 'Copyright &copy; 2019-2020 iBug'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://vlab.ustc.edu.cn/'
    - type: 'github'
      link: 'https://github.com/USTC-vlab'

extra_javascript:
  - assets/js/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list

nav:
  - 概览: index.md
  - SSH 证书认证: ssh-ca.md
  - 网络配置: networking.md

  - 旧版本:
    - 第一代: history/gen1.md
