#!/bin/bash -e

SRC="/etc/pve/nodes/pv1"
DSTROOT="/etc/pve/nodes"

scp web:/etc/acme.sh/ibuglab.com/ibuglab.com.key "$SRC/pveproxy-ssl.key"
scp web:/etc/acme.sh/ibuglab.com/fullchain.cer "$SRC/pveproxy-ssl.pem"
systemctl reload pveproxy.service vlab-pve-agent.service

for DST in "$DSTROOT"/*; do
  [ "$DST" = "$SRC" ] && continue
  node="$(basename "$DST")"
  cp "$SRC/pveproxy-ssl.key" "$SRC/pveproxy-ssl.pem" "$DST/"
  ssh "$node" 'systemctl reload pveproxy.service' &
  scp /etc/hosts "$node":/etc/hosts &
done
wait

# Proxmox Backup Server on pv1
DST="/etc/proxmox-backup"
cp "$SRC/pveproxy-ssl.key" "$DST/proxy.key"
cp "$SRC/pveproxy-ssl.pem" "$DST/proxy.pem"
systemctl reload proxmox-backup-proxy.service


#FP="$(openssl x509 -noout -fingerprint -sha256 -inform pem -in "$SRC/pveproxy-ssl.pem")"
#FP="${FP##*=}"
#pvesm set pbs --fingerprint "$FP"
